# coding: utf-8

"""
    Flowmill API Specification

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flowmill
from flowmill.models.grpc_get_latency_summary_request_v2 import GrpcGetLatencySummaryRequestV2  # noqa: E501
from flowmill.rest import ApiException


class TestGrpcGetLatencySummaryRequestV2(unittest.TestCase):
    """GrpcGetLatencySummaryRequestV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGrpcGetLatencySummaryRequestV2(self):
        """Test GrpcGetLatencySummaryRequestV2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = flowmill.models.grpc_get_latency_summary_request_v2.GrpcGetLatencySummaryRequestV2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
