# coding: utf-8

"""
    Flowmill API Specification

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flowmill
from flowmill.api.monitors_api import MonitorsApi  # noqa: E501
from flowmill.rest import ApiException


class TestMonitorsApi(unittest.TestCase):
    """MonitorsApi unit test stubs"""

    def setUp(self):
        self.api = flowmill.api.monitors_api.MonitorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_monitor(self):
        """Test case for delete_monitor

        """
        pass

    def test_evaluate_monitor(self):
        """Test case for evaluate_monitor

        """
        pass

    def test_get_monitor(self):
        """Test case for get_monitor

        """
        pass

    def test_get_monitor2(self):
        """Test case for get_monitor2

        """
        pass

    def test_post_monitor(self):
        """Test case for post_monitor

        """
        pass

    def test_put_monitor(self):
        """Test case for put_monitor

        """
        pass


if __name__ == '__main__':
    unittest.main()
