# coding: utf-8

"""
    Flowmill API Specification

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flowmill
from flowmill.models.grpc_update_alert_status_request import GrpcUpdateAlertStatusRequest  # noqa: E501
from flowmill.rest import ApiException


class TestGrpcUpdateAlertStatusRequest(unittest.TestCase):
    """GrpcUpdateAlertStatusRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGrpcUpdateAlertStatusRequest(self):
        """Test GrpcUpdateAlertStatusRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = flowmill.models.grpc_update_alert_status_request.GrpcUpdateAlertStatusRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
