# coding: utf-8

"""
    Flowmill API Specification

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flowmill
from flowmill.models.get_agent_info_response_agent_instance import GetAgentInfoResponseAgentInstance  # noqa: E501
from flowmill.rest import ApiException


class TestGetAgentInfoResponseAgentInstance(unittest.TestCase):
    """GetAgentInfoResponseAgentInstance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAgentInfoResponseAgentInstance(self):
        """Test GetAgentInfoResponseAgentInstance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = flowmill.models.get_agent_info_response_agent_instance.GetAgentInfoResponseAgentInstance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
