# coding: utf-8

"""
    Flowmill API Specification

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flowmill
from flowmill.models.grpc_get_traffic_stats_request_v2 import GrpcGetTrafficStatsRequestV2  # noqa: E501
from flowmill.rest import ApiException


class TestGrpcGetTrafficStatsRequestV2(unittest.TestCase):
    """GrpcGetTrafficStatsRequestV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGrpcGetTrafficStatsRequestV2(self):
        """Test GrpcGetTrafficStatsRequestV2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = flowmill.models.grpc_get_traffic_stats_request_v2.GrpcGetTrafficStatsRequestV2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
