# coding: utf-8

"""
    Flowmill API Specification

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flowmill
from flowmill.api.experimental_service_api import ExperimentalServiceApi  # noqa: E501
from flowmill.rest import ApiException


class TestExperimentalServiceApi(unittest.TestCase):
    """ExperimentalServiceApi unit test stubs"""

    def setUp(self):
        self.api = flowmill.api.experimental_service_api.ExperimentalServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_cost_table(self):
        """Test case for get_cost_table

        """
        pass

    def test_get_summary_table(self):
        """Test case for get_summary_table

        """
        pass


if __name__ == '__main__':
    unittest.main()
