# coding: utf-8

"""
    Flowmill API Specification

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flowmill
from flowmill.models.grpc_time_series_request_v2 import GrpcTimeSeriesRequestV2  # noqa: E501
from flowmill.rest import ApiException


class TestGrpcTimeSeriesRequestV2(unittest.TestCase):
    """GrpcTimeSeriesRequestV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGrpcTimeSeriesRequestV2(self):
        """Test GrpcTimeSeriesRequestV2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = flowmill.models.grpc_time_series_request_v2.GrpcTimeSeriesRequestV2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
