# coding: utf-8

"""
    Flowmill API Specification

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AutocompleteRequestV2LabelSidePair(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'label': 'str',
        'side': 'AutocompleteRequestV2Side'
    }

    attribute_map = {
        'label': 'label',
        'side': 'side'
    }

    def __init__(self, label=None, side=None):  # noqa: E501
        """AutocompleteRequestV2LabelSidePair - a model defined in Swagger"""  # noqa: E501

        self._label = None
        self._side = None
        self.discriminator = None

        if label is not None:
            self.label = label
        if side is not None:
            self.side = side

    @property
    def label(self):
        """Gets the label of this AutocompleteRequestV2LabelSidePair.  # noqa: E501


        :return: The label of this AutocompleteRequestV2LabelSidePair.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this AutocompleteRequestV2LabelSidePair.


        :param label: The label of this AutocompleteRequestV2LabelSidePair.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def side(self):
        """Gets the side of this AutocompleteRequestV2LabelSidePair.  # noqa: E501


        :return: The side of this AutocompleteRequestV2LabelSidePair.  # noqa: E501
        :rtype: AutocompleteRequestV2Side
        """
        return self._side

    @side.setter
    def side(self, side):
        """Sets the side of this AutocompleteRequestV2LabelSidePair.


        :param side: The side of this AutocompleteRequestV2LabelSidePair.  # noqa: E501
        :type: AutocompleteRequestV2Side
        """

        self._side = side

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AutocompleteRequestV2LabelSidePair, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AutocompleteRequestV2LabelSidePair):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
