# coding: utf-8

"""
    Flowmill API Specification

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GrpcPagedAlertsList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'alerts': 'list[GrpcAlert]',
        'offset': 'str',
        'count': 'str'
    }

    attribute_map = {
        'alerts': 'alerts',
        'offset': 'offset',
        'count': 'count'
    }

    def __init__(self, alerts=None, offset=None, count=None):  # noqa: E501
        """GrpcPagedAlertsList - a model defined in Swagger"""  # noqa: E501

        self._alerts = None
        self._offset = None
        self._count = None
        self.discriminator = None

        if alerts is not None:
            self.alerts = alerts
        if offset is not None:
            self.offset = offset
        if count is not None:
            self.count = count

    @property
    def alerts(self):
        """Gets the alerts of this GrpcPagedAlertsList.  # noqa: E501


        :return: The alerts of this GrpcPagedAlertsList.  # noqa: E501
        :rtype: list[GrpcAlert]
        """
        return self._alerts

    @alerts.setter
    def alerts(self, alerts):
        """Sets the alerts of this GrpcPagedAlertsList.


        :param alerts: The alerts of this GrpcPagedAlertsList.  # noqa: E501
        :type: list[GrpcAlert]
        """

        self._alerts = alerts

    @property
    def offset(self):
        """Gets the offset of this GrpcPagedAlertsList.  # noqa: E501


        :return: The offset of this GrpcPagedAlertsList.  # noqa: E501
        :rtype: str
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this GrpcPagedAlertsList.


        :param offset: The offset of this GrpcPagedAlertsList.  # noqa: E501
        :type: str
        """

        self._offset = offset

    @property
    def count(self):
        """Gets the count of this GrpcPagedAlertsList.  # noqa: E501


        :return: The count of this GrpcPagedAlertsList.  # noqa: E501
        :rtype: str
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this GrpcPagedAlertsList.


        :param count: The count of this GrpcPagedAlertsList.  # noqa: E501
        :type: str
        """

        self._count = count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GrpcPagedAlertsList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GrpcPagedAlertsList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
