# coding: utf-8

"""
    Flowmill API Specification

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GrpcEntityTimeseriesResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'timeseries': 'list[GrpcEntityTimeseriesList]'
    }

    attribute_map = {
        'timeseries': 'timeseries'
    }

    def __init__(self, timeseries=None):  # noqa: E501
        """GrpcEntityTimeseriesResponse - a model defined in Swagger"""  # noqa: E501

        self._timeseries = None
        self.discriminator = None

        if timeseries is not None:
            self.timeseries = timeseries

    @property
    def timeseries(self):
        """Gets the timeseries of this GrpcEntityTimeseriesResponse.  # noqa: E501

        Structures that include (metric, timeseries) for the specified query.  These structures are sorted by _______.  Note: we need to define a meaningful sort order for this list. We could either sort by the order of the request.metrics field or alphabetically by the timeseries.metric field.  # noqa: E501

        :return: The timeseries of this GrpcEntityTimeseriesResponse.  # noqa: E501
        :rtype: list[GrpcEntityTimeseriesList]
        """
        return self._timeseries

    @timeseries.setter
    def timeseries(self, timeseries):
        """Sets the timeseries of this GrpcEntityTimeseriesResponse.

        Structures that include (metric, timeseries) for the specified query.  These structures are sorted by _______.  Note: we need to define a meaningful sort order for this list. We could either sort by the order of the request.metrics field or alphabetically by the timeseries.metric field.  # noqa: E501

        :param timeseries: The timeseries of this GrpcEntityTimeseriesResponse.  # noqa: E501
        :type: list[GrpcEntityTimeseriesList]
        """

        self._timeseries = timeseries

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GrpcEntityTimeseriesResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GrpcEntityTimeseriesResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
