# coding: utf-8

"""
    Flowmill API Specification

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GrpcGetLatencySummaryResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'latency_summaries': 'list[GrpcLatencySummary]'
    }

    attribute_map = {
        'latency_summaries': 'latencySummaries'
    }

    def __init__(self, latency_summaries=None):  # noqa: E501
        """GrpcGetLatencySummaryResponse - a model defined in Swagger"""  # noqa: E501

        self._latency_summaries = None
        self.discriminator = None

        if latency_summaries is not None:
            self.latency_summaries = latency_summaries

    @property
    def latency_summaries(self):
        """Gets the latency_summaries of this GrpcGetLatencySummaryResponse.  # noqa: E501


        :return: The latency_summaries of this GrpcGetLatencySummaryResponse.  # noqa: E501
        :rtype: list[GrpcLatencySummary]
        """
        return self._latency_summaries

    @latency_summaries.setter
    def latency_summaries(self, latency_summaries):
        """Sets the latency_summaries of this GrpcGetLatencySummaryResponse.


        :param latency_summaries: The latency_summaries of this GrpcGetLatencySummaryResponse.  # noqa: E501
        :type: list[GrpcLatencySummary]
        """

        self._latency_summaries = latency_summaries

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GrpcGetLatencySummaryResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GrpcGetLatencySummaryResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
