# coding: utf-8

"""
    Flowmill API Specification

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GrpcEntityTimeseries(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'labels': 'list[GrpcLabel]',
        'values': 'list[float]'
    }

    attribute_map = {
        'labels': 'labels',
        'values': 'values'
    }

    def __init__(self, labels=None, values=None):  # noqa: E501
        """GrpcEntityTimeseries - a model defined in Swagger"""  # noqa: E501

        self._labels = None
        self._values = None
        self.discriminator = None

        if labels is not None:
            self.labels = labels
        if values is not None:
            self.values = values

    @property
    def labels(self):
        """Gets the labels of this GrpcEntityTimeseries.  # noqa: E501

        Labels identifying this timeseries.  We enforce that these labels are alphabetically sorted by their `name`.  # noqa: E501

        :return: The labels of this GrpcEntityTimeseries.  # noqa: E501
        :rtype: list[GrpcLabel]
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this GrpcEntityTimeseries.

        Labels identifying this timeseries.  We enforce that these labels are alphabetically sorted by their `name`.  # noqa: E501

        :param labels: The labels of this GrpcEntityTimeseries.  # noqa: E501
        :type: list[GrpcLabel]
        """

        self._labels = labels

    @property
    def values(self):
        """Gets the values of this GrpcEntityTimeseries.  # noqa: E501

        List of points for this timeseries.  The points in values correspond to TSDB samples aggregated over time ranges:    - values[0] is the range (start, start + (step)]    - values[1] is the range (start + step, start + (step * 2)]    - values[2] is the range (start + (step * 2), start + (step * 3)]      ...    - values[i] is the range (start + (step * i), start + (step * (i +    1))]  If we do not have samples for a given value, then the API will either:   1) fill the value with a 0 if the pipeline uses \"no samples\" to encode      a zero value.   2) fill the value with a -1 if the pipeline uses \"no samples\" to mean      that we have no data for a given time range.  Our documentation *must* explicitly include a description of which metrics will get 0 or -1 for no sample periods.  # noqa: E501

        :return: The values of this GrpcEntityTimeseries.  # noqa: E501
        :rtype: list[float]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this GrpcEntityTimeseries.

        List of points for this timeseries.  The points in values correspond to TSDB samples aggregated over time ranges:    - values[0] is the range (start, start + (step)]    - values[1] is the range (start + step, start + (step * 2)]    - values[2] is the range (start + (step * 2), start + (step * 3)]      ...    - values[i] is the range (start + (step * i), start + (step * (i +    1))]  If we do not have samples for a given value, then the API will either:   1) fill the value with a 0 if the pipeline uses \"no samples\" to encode      a zero value.   2) fill the value with a -1 if the pipeline uses \"no samples\" to mean      that we have no data for a given time range.  Our documentation *must* explicitly include a description of which metrics will get 0 or -1 for no sample periods.  # noqa: E501

        :param values: The values of this GrpcEntityTimeseries.  # noqa: E501
        :type: list[float]
        """

        self._values = values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GrpcEntityTimeseries, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GrpcEntityTimeseries):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
