# coding: utf-8

"""
    Flowmill API Specification

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GrpcCostTableRow(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'source_labels': 'list[GrpcLabel]',
        'destination_labels': 'list[GrpcLabel]',
        'cross_az': 'GrpcCostTableBreakdown',
        'egress': 'GrpcCostTableBreakdown',
        'totals': 'GrpcCostTableBreakdown'
    }

    attribute_map = {
        'source_labels': 'sourceLabels',
        'destination_labels': 'destinationLabels',
        'cross_az': 'crossAz',
        'egress': 'egress',
        'totals': 'totals'
    }

    def __init__(self, source_labels=None, destination_labels=None, cross_az=None, egress=None, totals=None):  # noqa: E501
        """GrpcCostTableRow - a model defined in Swagger"""  # noqa: E501

        self._source_labels = None
        self._destination_labels = None
        self._cross_az = None
        self._egress = None
        self._totals = None
        self.discriminator = None

        if source_labels is not None:
            self.source_labels = source_labels
        if destination_labels is not None:
            self.destination_labels = destination_labels
        if cross_az is not None:
            self.cross_az = cross_az
        if egress is not None:
            self.egress = egress
        if totals is not None:
            self.totals = totals

    @property
    def source_labels(self):
        """Gets the source_labels of this GrpcCostTableRow.  # noqa: E501


        :return: The source_labels of this GrpcCostTableRow.  # noqa: E501
        :rtype: list[GrpcLabel]
        """
        return self._source_labels

    @source_labels.setter
    def source_labels(self, source_labels):
        """Sets the source_labels of this GrpcCostTableRow.


        :param source_labels: The source_labels of this GrpcCostTableRow.  # noqa: E501
        :type: list[GrpcLabel]
        """

        self._source_labels = source_labels

    @property
    def destination_labels(self):
        """Gets the destination_labels of this GrpcCostTableRow.  # noqa: E501


        :return: The destination_labels of this GrpcCostTableRow.  # noqa: E501
        :rtype: list[GrpcLabel]
        """
        return self._destination_labels

    @destination_labels.setter
    def destination_labels(self, destination_labels):
        """Sets the destination_labels of this GrpcCostTableRow.


        :param destination_labels: The destination_labels of this GrpcCostTableRow.  # noqa: E501
        :type: list[GrpcLabel]
        """

        self._destination_labels = destination_labels

    @property
    def cross_az(self):
        """Gets the cross_az of this GrpcCostTableRow.  # noqa: E501


        :return: The cross_az of this GrpcCostTableRow.  # noqa: E501
        :rtype: GrpcCostTableBreakdown
        """
        return self._cross_az

    @cross_az.setter
    def cross_az(self, cross_az):
        """Sets the cross_az of this GrpcCostTableRow.


        :param cross_az: The cross_az of this GrpcCostTableRow.  # noqa: E501
        :type: GrpcCostTableBreakdown
        """

        self._cross_az = cross_az

    @property
    def egress(self):
        """Gets the egress of this GrpcCostTableRow.  # noqa: E501


        :return: The egress of this GrpcCostTableRow.  # noqa: E501
        :rtype: GrpcCostTableBreakdown
        """
        return self._egress

    @egress.setter
    def egress(self, egress):
        """Sets the egress of this GrpcCostTableRow.


        :param egress: The egress of this GrpcCostTableRow.  # noqa: E501
        :type: GrpcCostTableBreakdown
        """

        self._egress = egress

    @property
    def totals(self):
        """Gets the totals of this GrpcCostTableRow.  # noqa: E501


        :return: The totals of this GrpcCostTableRow.  # noqa: E501
        :rtype: GrpcCostTableBreakdown
        """
        return self._totals

    @totals.setter
    def totals(self, totals):
        """Sets the totals of this GrpcCostTableRow.


        :param totals: The totals of this GrpcCostTableRow.  # noqa: E501
        :type: GrpcCostTableBreakdown
        """

        self._totals = totals

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GrpcCostTableRow, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GrpcCostTableRow):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
