# coding: utf-8

"""
    Flowmill API Specification

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GrpcListSlackAuthorizedResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'team_list': 'list[ListSlackAuthorizedResponseTeam]'
    }

    attribute_map = {
        'team_list': 'teamList'
    }

    def __init__(self, team_list=None):  # noqa: E501
        """GrpcListSlackAuthorizedResponse - a model defined in Swagger"""  # noqa: E501

        self._team_list = None
        self.discriminator = None

        if team_list is not None:
            self.team_list = team_list

    @property
    def team_list(self):
        """Gets the team_list of this GrpcListSlackAuthorizedResponse.  # noqa: E501


        :return: The team_list of this GrpcListSlackAuthorizedResponse.  # noqa: E501
        :rtype: list[ListSlackAuthorizedResponseTeam]
        """
        return self._team_list

    @team_list.setter
    def team_list(self, team_list):
        """Sets the team_list of this GrpcListSlackAuthorizedResponse.


        :param team_list: The team_list of this GrpcListSlackAuthorizedResponse.  # noqa: E501
        :type: list[ListSlackAuthorizedResponseTeam]
        """

        self._team_list = team_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GrpcListSlackAuthorizedResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GrpcListSlackAuthorizedResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
