# coding: utf-8

"""
    Flowmill API Specification

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GrpcGetAgentInfoResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'agent_timeseries': 'list[GetAgentInfoResponseAgentCount]',
        'total_agents': 'int',
        'agent_instances': 'list[GetAgentInfoResponseAgentInstance]'
    }

    attribute_map = {
        'agent_timeseries': 'agentTimeseries',
        'total_agents': 'totalAgents',
        'agent_instances': 'agentInstances'
    }

    def __init__(self, agent_timeseries=None, total_agents=None, agent_instances=None):  # noqa: E501
        """GrpcGetAgentInfoResponse - a model defined in Swagger"""  # noqa: E501

        self._agent_timeseries = None
        self._total_agents = None
        self._agent_instances = None
        self.discriminator = None

        if agent_timeseries is not None:
            self.agent_timeseries = agent_timeseries
        if total_agents is not None:
            self.total_agents = total_agents
        if agent_instances is not None:
            self.agent_instances = agent_instances

    @property
    def agent_timeseries(self):
        """Gets the agent_timeseries of this GrpcGetAgentInfoResponse.  # noqa: E501


        :return: The agent_timeseries of this GrpcGetAgentInfoResponse.  # noqa: E501
        :rtype: list[GetAgentInfoResponseAgentCount]
        """
        return self._agent_timeseries

    @agent_timeseries.setter
    def agent_timeseries(self, agent_timeseries):
        """Sets the agent_timeseries of this GrpcGetAgentInfoResponse.


        :param agent_timeseries: The agent_timeseries of this GrpcGetAgentInfoResponse.  # noqa: E501
        :type: list[GetAgentInfoResponseAgentCount]
        """

        self._agent_timeseries = agent_timeseries

    @property
    def total_agents(self):
        """Gets the total_agents of this GrpcGetAgentInfoResponse.  # noqa: E501


        :return: The total_agents of this GrpcGetAgentInfoResponse.  # noqa: E501
        :rtype: int
        """
        return self._total_agents

    @total_agents.setter
    def total_agents(self, total_agents):
        """Sets the total_agents of this GrpcGetAgentInfoResponse.


        :param total_agents: The total_agents of this GrpcGetAgentInfoResponse.  # noqa: E501
        :type: int
        """

        self._total_agents = total_agents

    @property
    def agent_instances(self):
        """Gets the agent_instances of this GrpcGetAgentInfoResponse.  # noqa: E501


        :return: The agent_instances of this GrpcGetAgentInfoResponse.  # noqa: E501
        :rtype: list[GetAgentInfoResponseAgentInstance]
        """
        return self._agent_instances

    @agent_instances.setter
    def agent_instances(self, agent_instances):
        """Sets the agent_instances of this GrpcGetAgentInfoResponse.


        :param agent_instances: The agent_instances of this GrpcGetAgentInfoResponse.  # noqa: E501
        :type: list[GetAgentInfoResponseAgentInstance]
        """

        self._agent_instances = agent_instances

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GrpcGetAgentInfoResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GrpcGetAgentInfoResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
