# coding: utf-8

"""
    Flowmill API Specification

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GrpcGetSummaryTableRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'end': 'datetime',
        'duration': 'str',
        'num_steps': 'int',
        'metrics': 'list[str]',
        'source_filters': 'list[GrpcFilter]',
        'destination_filters': 'list[GrpcFilter]',
        'source_grouping': 'list[str]',
        'destination_grouping': 'list[str]',
        'directionality': 'GrpcDirectionality',
        'no_rollups': 'bool',
        'no_zero_padding': 'bool'
    }

    attribute_map = {
        'end': 'end',
        'duration': 'duration',
        'num_steps': 'numSteps',
        'metrics': 'metrics',
        'source_filters': 'sourceFilters',
        'destination_filters': 'destinationFilters',
        'source_grouping': 'sourceGrouping',
        'destination_grouping': 'destinationGrouping',
        'directionality': 'directionality',
        'no_rollups': 'noRollups',
        'no_zero_padding': 'noZeroPadding'
    }

    def __init__(self, end=None, duration=None, num_steps=None, metrics=None, source_filters=None, destination_filters=None, source_grouping=None, destination_grouping=None, directionality=None, no_rollups=None, no_zero_padding=None):  # noqa: E501
        """GrpcGetSummaryTableRequest - a model defined in Swagger"""  # noqa: E501

        self._end = None
        self._duration = None
        self._num_steps = None
        self._metrics = None
        self._source_filters = None
        self._destination_filters = None
        self._source_grouping = None
        self._destination_grouping = None
        self._directionality = None
        self._no_rollups = None
        self._no_zero_padding = None
        self.discriminator = None

        if end is not None:
            self.end = end
        if duration is not None:
            self.duration = duration
        if num_steps is not None:
            self.num_steps = num_steps
        if metrics is not None:
            self.metrics = metrics
        if source_filters is not None:
            self.source_filters = source_filters
        if destination_filters is not None:
            self.destination_filters = destination_filters
        if source_grouping is not None:
            self.source_grouping = source_grouping
        if destination_grouping is not None:
            self.destination_grouping = destination_grouping
        if directionality is not None:
            self.directionality = directionality
        if no_rollups is not None:
            self.no_rollups = no_rollups
        if no_zero_padding is not None:
            self.no_zero_padding = no_zero_padding

    @property
    def end(self):
        """Gets the end of this GrpcGetSummaryTableRequest.  # noqa: E501

        See GetTimeSeriesRequestV2 for a description of end, duration, and num_steps.  # noqa: E501

        :return: The end of this GrpcGetSummaryTableRequest.  # noqa: E501
        :rtype: datetime
        """
        return self._end

    @end.setter
    def end(self, end):
        """Sets the end of this GrpcGetSummaryTableRequest.

        See GetTimeSeriesRequestV2 for a description of end, duration, and num_steps.  # noqa: E501

        :param end: The end of this GrpcGetSummaryTableRequest.  # noqa: E501
        :type: datetime
        """

        self._end = end

    @property
    def duration(self):
        """Gets the duration of this GrpcGetSummaryTableRequest.  # noqa: E501


        :return: The duration of this GrpcGetSummaryTableRequest.  # noqa: E501
        :rtype: str
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this GrpcGetSummaryTableRequest.


        :param duration: The duration of this GrpcGetSummaryTableRequest.  # noqa: E501
        :type: str
        """

        self._duration = duration

    @property
    def num_steps(self):
        """Gets the num_steps of this GrpcGetSummaryTableRequest.  # noqa: E501


        :return: The num_steps of this GrpcGetSummaryTableRequest.  # noqa: E501
        :rtype: int
        """
        return self._num_steps

    @num_steps.setter
    def num_steps(self, num_steps):
        """Sets the num_steps of this GrpcGetSummaryTableRequest.


        :param num_steps: The num_steps of this GrpcGetSummaryTableRequest.  # noqa: E501
        :type: int
        """

        self._num_steps = num_steps

    @property
    def metrics(self):
        """Gets the metrics of this GrpcGetSummaryTableRequest.  # noqa: E501

        List of metrics to be returned for each row in the table.  When a row has no values for a specified metric, then that metric will be ommitted in the response.  # noqa: E501

        :return: The metrics of this GrpcGetSummaryTableRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._metrics

    @metrics.setter
    def metrics(self, metrics):
        """Sets the metrics of this GrpcGetSummaryTableRequest.

        List of metrics to be returned for each row in the table.  When a row has no values for a specified metric, then that metric will be ommitted in the response.  # noqa: E501

        :param metrics: The metrics of this GrpcGetSummaryTableRequest.  # noqa: E501
        :type: list[str]
        """

        self._metrics = metrics

    @property
    def source_filters(self):
        """Gets the source_filters of this GrpcGetSummaryTableRequest.  # noqa: E501


        :return: The source_filters of this GrpcGetSummaryTableRequest.  # noqa: E501
        :rtype: list[GrpcFilter]
        """
        return self._source_filters

    @source_filters.setter
    def source_filters(self, source_filters):
        """Sets the source_filters of this GrpcGetSummaryTableRequest.


        :param source_filters: The source_filters of this GrpcGetSummaryTableRequest.  # noqa: E501
        :type: list[GrpcFilter]
        """

        self._source_filters = source_filters

    @property
    def destination_filters(self):
        """Gets the destination_filters of this GrpcGetSummaryTableRequest.  # noqa: E501


        :return: The destination_filters of this GrpcGetSummaryTableRequest.  # noqa: E501
        :rtype: list[GrpcFilter]
        """
        return self._destination_filters

    @destination_filters.setter
    def destination_filters(self, destination_filters):
        """Sets the destination_filters of this GrpcGetSummaryTableRequest.


        :param destination_filters: The destination_filters of this GrpcGetSummaryTableRequest.  # noqa: E501
        :type: list[GrpcFilter]
        """

        self._destination_filters = destination_filters

    @property
    def source_grouping(self):
        """Gets the source_grouping of this GrpcGetSummaryTableRequest.  # noqa: E501


        :return: The source_grouping of this GrpcGetSummaryTableRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._source_grouping

    @source_grouping.setter
    def source_grouping(self, source_grouping):
        """Sets the source_grouping of this GrpcGetSummaryTableRequest.


        :param source_grouping: The source_grouping of this GrpcGetSummaryTableRequest.  # noqa: E501
        :type: list[str]
        """

        self._source_grouping = source_grouping

    @property
    def destination_grouping(self):
        """Gets the destination_grouping of this GrpcGetSummaryTableRequest.  # noqa: E501


        :return: The destination_grouping of this GrpcGetSummaryTableRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._destination_grouping

    @destination_grouping.setter
    def destination_grouping(self, destination_grouping):
        """Sets the destination_grouping of this GrpcGetSummaryTableRequest.


        :param destination_grouping: The destination_grouping of this GrpcGetSummaryTableRequest.  # noqa: E501
        :type: list[str]
        """

        self._destination_grouping = destination_grouping

    @property
    def directionality(self):
        """Gets the directionality of this GrpcGetSummaryTableRequest.  # noqa: E501


        :return: The directionality of this GrpcGetSummaryTableRequest.  # noqa: E501
        :rtype: GrpcDirectionality
        """
        return self._directionality

    @directionality.setter
    def directionality(self, directionality):
        """Sets the directionality of this GrpcGetSummaryTableRequest.


        :param directionality: The directionality of this GrpcGetSummaryTableRequest.  # noqa: E501
        :type: GrpcDirectionality
        """

        self._directionality = directionality

    @property
    def no_rollups(self):
        """Gets the no_rollups of this GrpcGetSummaryTableRequest.  # noqa: E501


        :return: The no_rollups of this GrpcGetSummaryTableRequest.  # noqa: E501
        :rtype: bool
        """
        return self._no_rollups

    @no_rollups.setter
    def no_rollups(self, no_rollups):
        """Sets the no_rollups of this GrpcGetSummaryTableRequest.


        :param no_rollups: The no_rollups of this GrpcGetSummaryTableRequest.  # noqa: E501
        :type: bool
        """

        self._no_rollups = no_rollups

    @property
    def no_zero_padding(self):
        """Gets the no_zero_padding of this GrpcGetSummaryTableRequest.  # noqa: E501


        :return: The no_zero_padding of this GrpcGetSummaryTableRequest.  # noqa: E501
        :rtype: bool
        """
        return self._no_zero_padding

    @no_zero_padding.setter
    def no_zero_padding(self, no_zero_padding):
        """Sets the no_zero_padding of this GrpcGetSummaryTableRequest.


        :param no_zero_padding: The no_zero_padding of this GrpcGetSummaryTableRequest.  # noqa: E501
        :type: bool
        """

        self._no_zero_padding = no_zero_padding

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GrpcGetSummaryTableRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GrpcGetSummaryTableRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
