# coding: utf-8

"""
    Flowmill API Specification

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ListUsersResponseUserStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user_id': 'str',
        'email': 'str',
        'role': 'str',
        'status': 'str',
        'last_used': 'datetime'
    }

    attribute_map = {
        'user_id': 'userId',
        'email': 'email',
        'role': 'role',
        'status': 'status',
        'last_used': 'lastUsed'
    }

    def __init__(self, user_id=None, email=None, role=None, status=None, last_used=None):  # noqa: E501
        """ListUsersResponseUserStatus - a model defined in Swagger"""  # noqa: E501

        self._user_id = None
        self._email = None
        self._role = None
        self._status = None
        self._last_used = None
        self.discriminator = None

        if user_id is not None:
            self.user_id = user_id
        if email is not None:
            self.email = email
        if role is not None:
            self.role = role
        if status is not None:
            self.status = status
        if last_used is not None:
            self.last_used = last_used

    @property
    def user_id(self):
        """Gets the user_id of this ListUsersResponseUserStatus.  # noqa: E501


        :return: The user_id of this ListUsersResponseUserStatus.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this ListUsersResponseUserStatus.


        :param user_id: The user_id of this ListUsersResponseUserStatus.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    @property
    def email(self):
        """Gets the email of this ListUsersResponseUserStatus.  # noqa: E501


        :return: The email of this ListUsersResponseUserStatus.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this ListUsersResponseUserStatus.


        :param email: The email of this ListUsersResponseUserStatus.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def role(self):
        """Gets the role of this ListUsersResponseUserStatus.  # noqa: E501


        :return: The role of this ListUsersResponseUserStatus.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this ListUsersResponseUserStatus.


        :param role: The role of this ListUsersResponseUserStatus.  # noqa: E501
        :type: str
        """

        self._role = role

    @property
    def status(self):
        """Gets the status of this ListUsersResponseUserStatus.  # noqa: E501


        :return: The status of this ListUsersResponseUserStatus.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ListUsersResponseUserStatus.


        :param status: The status of this ListUsersResponseUserStatus.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def last_used(self):
        """Gets the last_used of this ListUsersResponseUserStatus.  # noqa: E501


        :return: The last_used of this ListUsersResponseUserStatus.  # noqa: E501
        :rtype: datetime
        """
        return self._last_used

    @last_used.setter
    def last_used(self, last_used):
        """Sets the last_used of this ListUsersResponseUserStatus.


        :param last_used: The last_used of this ListUsersResponseUserStatus.  # noqa: E501
        :type: datetime
        """

        self._last_used = last_used

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ListUsersResponseUserStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListUsersResponseUserStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
