# coding: utf-8

"""
    Flowmill API Specification

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ListKeysResponseSingleKey(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key_id': 'str',
        'user_id': 'str',
        'created_at': 'datetime',
        'last_used': 'datetime'
    }

    attribute_map = {
        'key_id': 'keyId',
        'user_id': 'userId',
        'created_at': 'createdAt',
        'last_used': 'lastUsed'
    }

    def __init__(self, key_id=None, user_id=None, created_at=None, last_used=None):  # noqa: E501
        """ListKeysResponseSingleKey - a model defined in Swagger"""  # noqa: E501

        self._key_id = None
        self._user_id = None
        self._created_at = None
        self._last_used = None
        self.discriminator = None

        if key_id is not None:
            self.key_id = key_id
        if user_id is not None:
            self.user_id = user_id
        if created_at is not None:
            self.created_at = created_at
        if last_used is not None:
            self.last_used = last_used

    @property
    def key_id(self):
        """Gets the key_id of this ListKeysResponseSingleKey.  # noqa: E501


        :return: The key_id of this ListKeysResponseSingleKey.  # noqa: E501
        :rtype: str
        """
        return self._key_id

    @key_id.setter
    def key_id(self, key_id):
        """Sets the key_id of this ListKeysResponseSingleKey.


        :param key_id: The key_id of this ListKeysResponseSingleKey.  # noqa: E501
        :type: str
        """

        self._key_id = key_id

    @property
    def user_id(self):
        """Gets the user_id of this ListKeysResponseSingleKey.  # noqa: E501


        :return: The user_id of this ListKeysResponseSingleKey.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this ListKeysResponseSingleKey.


        :param user_id: The user_id of this ListKeysResponseSingleKey.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    @property
    def created_at(self):
        """Gets the created_at of this ListKeysResponseSingleKey.  # noqa: E501


        :return: The created_at of this ListKeysResponseSingleKey.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ListKeysResponseSingleKey.


        :param created_at: The created_at of this ListKeysResponseSingleKey.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def last_used(self):
        """Gets the last_used of this ListKeysResponseSingleKey.  # noqa: E501


        :return: The last_used of this ListKeysResponseSingleKey.  # noqa: E501
        :rtype: datetime
        """
        return self._last_used

    @last_used.setter
    def last_used(self, last_used):
        """Sets the last_used of this ListKeysResponseSingleKey.


        :param last_used: The last_used of this ListKeysResponseSingleKey.  # noqa: E501
        :type: datetime
        """

        self._last_used = last_used

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ListKeysResponseSingleKey, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListKeysResponseSingleKey):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
